### PR TITLE
Create playground and add camera movement

### PR DESCRIPTION
**Pull request by Arnau77**
It has been created the playground bones (the floor and walls with its mesurements and also some "ceilings" to separate visually the four parts that will constitute the playground).
It has been also added a camera movement script that follows the player when it's moving and stops when reaches the end determined by the walls.

### CODE REVIEW

**Review by daskza19 — CHANGES_REQUESTED** [review]
I think we can use boundaries with Cinemachine package. With this actual implementation we don't use a package we already have (worse performance). With cinemachine is more visual to modify the boundaries. There is a video of how I think we can implementate it: https://youtu.be/e1-DOaHU5D4

**Comment by Arnau77** [comment]
The camera script has been deleted and now the following function is done by cinemachine

**Review by daskza19 — APPROVED** [review]
Much better! Cool implementation and very smooth. Congratulations! 👏😎

**Review by daskza19 — CHANGES_REQUESTED** [review]
SC_Player script does not follow the Naming Convention in TDD. In theory this must have the name ST_player.cs

**Comment by Arnau77** [comment]
You're right, I got confused, changed it.

**Review by daskza19 — APPROVED** [review]

**Review by JBGelsenorJ — APPROVED** [review]

**Review by Rugiacreed — APPROVED** [review]

**Pull request merged**
